Airflow protoype
stackabletech/airflow-operator pull request #1
Opened 2022-01-26 15:21 UTC by adwk67

- The airflow operator has two external dependencies (postgresql and redis) and deploys 3 components
- The database is used for storing user and job data
- The queue is used for distributing jobs
- Airflow offers 4 executor modes: Sequential (jobs are started in series/sequence), Local (whereby a minimal amount of parallelism is offered as all jobs run in the same service), Celery (jobs are distributed amongst the worker nodes) and Kubernetes (a pod is started, used and then destroyed for each job): the airflow operator can be configured to use the first three of these (the example cluster .yaml uses the CeleryExecutor)
- 3 different components are deployed: the webserver, a scheduler and a worker (which uses the executor mentioned above)

To test locally:
```
kind delete clusters kind
kind create cluster

# external dependencies
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install airflow bitnami/postgresql \
    --set postgresqlUsername=airflow \
    --set postgresqlPassword=airflow \
    --set postgresqlDatabase=airflow

helm install redis bitnami/redis \
    --set auth.password=redis

# push secret
kubectl apply -f examples/simple-airflow-credentials-secret.yaml

# push CRDs
cargo run -- crd | kubectl apply -f -
kubectl get crds

# start operator
cargo run -- run
```
And then:
```
kubectl apply -f examples/init.command.example.yaml
kubectl apply -f examples/simple-airflow-cluster.yaml
```
Closes #155

2022-01-28 12:29 UTC, siegfriedweber requested changes
The following issues must be fixed:
- The documentation (the `docs` directory) is missing.
- The changelog is missing.
- The license file is missing.
- The readme file should contain the badge with the build action status.
- The dependencies should be upgraded with `cargo update`.
- The init command still exists after the integration test has finished. When the operator is restarted then it runs into an error loop.

Airflow seems to work but there are some errors in the logs (e.g. that the workers cannot connect to redis) which I have to investigate further.

2022-01-28 12:50 UTC, siegfriedweber requested changes

2022-01-28 12:50 UTC, siegfriedweber commented on rust/operator-binary/src/airflow_controller.rs
> +    },
These errors are not used and can be removed.

2022-01-28 12:55 UTC, adwk67 commented on rust/crd/src/lib.rs
> +            // TODO this depends on the executor!
This will be covered in https://github.com/stackabletech/airflow-operator/issues/2

2022-01-31 08:50 UTC, siegfriedweber requested changes

2022-01-31 08:50 UTC, siegfriedweber commented on docs/modules/ROOT/pages/usage.adoc
> +will run and job tree will update automatically:
```suggestion
Click on an example DAG and then invoke the job: if the scheduler is correctly set up then the job
will run and the job tree will update automatically:
```

2022-01-31 08:50 UTC, siegfriedweber commented on rust/operator-binary/Cargo.toml
> +stackable-airflow-crd = { path = "../crd" }
```suggestion
stackable-airflow-crd = { path = "../crd" }
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.8.0" }
```

2022-01-31 08:50 UTC, siegfriedweber commented on docs/modules/ROOT/pages/usage.adoc
> +command initializes the dababase by creating the necessary database tables, creating the admin user
```suggestion
command initializes the database by creating the necessary database tables, creating the admin user
```

2022-01-31 08:50 UTC, siegfriedweber commented on docs/modules/ROOT/pages/usage.adoc
> +Set `spec.loadExamples` to `true` if you want the dababase populated with example data and
```suggestion
Set `spec.loadExamples` to `true` if you want the database populated with example data and
```

2022-01-31 15:00 UTC, siegfriedweber approved these changes
LGTM

2022-01-31 15:09 UTC, merged